# Generated by Django 5.0.1 on 2024-11-11 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.CharField(choices=[('Comida y Bebidas', 'Comida y Bebidas'), ('POSTRES', 'Postres y Dulces'), ('TECNOLOGIA', 'Tecnología y accesorios'), ('ROPA', 'Ropa y Moda'), ('ACCESORIOS', 'Accesorios'), ('LIBROS_PAPELERIA', 'Libros y Papelería'), ('MANUALIDADES', 'Manualidades'), ('SERVICIOS', 'Servicios'), ('HOGAR', 'Hogar y Decoración'), ('ENTRETENIMIENTO', 'Juegos y Entretenimiento'), ('DEPORTES', 'Deportes y Fitness'), ('OTROS', 'Otros')], default='OTROS', max_length=30)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuariosApp.producto')),
            ],
        ),
    ]
